name: Security check - ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stefanoeb/eslint-action@1.0.2
        continue-on-error: true